Initial Commit
virtee/snp pull request #1
Opened 2023-02-27 18:30 UTC by larrydewey

Initial re-working of the virtee/sev library for SEV-SNP only workloads.

2023-03-03 06:37 UTC, tylerfanelli requested changes
Mostly LGTM. Can we add some testing infrastructure for `cargo test`? Take the [sev library's tests directory](https://github.com/virtee/sev/tree/main/tests) for inspiration.

2023-03-03 22:11 UTC, larrydewey commented on src/firmware/linux/guest/types.rs
> +use serde_big_array::BigArray;
Correct, I was playing around with the feature, but decided to just use `serde` or `serde-big-array` instead. I missed these. Thanks!

2023-03-03 22:11 UTC, larrydewey commented on src/firmware/linux/guest/types.rs
> +use serde_big_array::BigArray;
Will fix in next commit

2023-03-03 22:31 UTC, larrydewey commented on Cargo.toml
> +uuid = { version = "^1.2" }
I do like this, and I have added it, but is there a way to conditionally add the feature? If the user optionally decides against using `serde`, it would be nice to have this removed.

2023-03-03 22:53 UTC, larrydewey commented on Cargo.toml
> +uuid = { version = "^1.2" }
nvm, I found it.

2023-03-06 11:52 UTC, mkulke reviewed
Some more suggestions, mostly stylistic. I wonder whether it might be a good idea to explicitly bail out on invalid input in the unsafe parts when dealing with raw pointers.

2023-03-06 11:52 UTC, mkulke commented on src/firmware/host/types.rs
> +    }
the clone isn't required I think?

```suggestion
        self.cert_type.to_string()
    }
```

2023-03-06 11:52 UTC, mkulke commented on src/firmware/linux/host/types.rs
> +            while cert_addr.ne(&cert_end) {
```suggestion
            while cert_addr != cert_end {
```

2023-03-06 16:56 UTC, larrydewey commented on src/firmware/guest/mod.rs
> +        }
I like this, but I created a new `SnpCertError`, and am returning that instead of using a `FirmwareError`. A host may decided not to provide these certificates, and this would be a valid Firmware state.

2023-03-06 17:03 UTC, larrydewey commented on src/firmware/host/mod.rs
> +        }
Originally I did a copy into a `mut T` to indicate that we intended for the value to change. We can cast this to a pointer, but it is a bit more C-like than I usually prefer.

2023-03-06 17:10 UTC, mkulke commented on src/firmware/host/mod.rs
> +        }
ah, but `copied_data` should just be an alias to `vector`, so vector can be passed to `parse_table` directly (we take ownership of it in the branch) and cast there in the arguments, it's probably a noop in compiled code.

2023-03-06 17:28 UTC, larrydewey commented on src/firmware/host/mod.rs
> +        }
Good point. Still getting used to functional paradigms.

2023-03-06 17:36 UTC, larrydewey commented on src/firmware/host/types.rs
> +        {
In this case, it should be okay, as the host may be checking if they have set a value or not. I think it should be okay in this case. Is there a use-case where you think we should return an error?

2023-03-07 08:37 UTC, mkulke commented on src/firmware/host/types.rs
> +        {
Ah, nevermind. I looked at the wrong struct. I suppose `None` is semantically legit is in both `config` and `certs` fields.

2023-03-08 03:20 UTC, tylerfanelli reviewed
Could you add the built in certs for Genoa?

2023-03-09 18:32 UTC, larrydewey commented
> Could you add the built in certs for Genoa?

Added

2023-03-22 18:47 UTC, tylerfanelli requested changes
Thanks Larry, I've left some feedback.

Note that the entire `src/tests` directory should be moved to just `tests/`.

2023-03-22 18:47 UTC, tylerfanelli commented on src/certs/builtin/genoa/mod.rs
> +const ARK: &[u8] = include_bytes!("ark.pem");
Since they are in PEM format, maybe we should use `openssl::x509::X509::from_pem()`?

2023-03-22 18:47 UTC, tylerfanelli commented on src/certs/builtin/milan/mod.rs
> +const ARK: &[u8] = include_bytes!("ark.pem");
Same here, `openssl::x509::X509::from_pem()` instead of `include_bytes()`.

2023-03-22 18:47 UTC, tylerfanelli commented on src/certs/ecdsa/mod.rs
> +pub struct Signature {
For formatting purposes, can we remove the space above `pub struct Signature {`?

2023-03-22 18:47 UTC, tylerfanelli commented on src/certs/rsa/mod.rs
> +// SPDX-License-Identifier: Apache-2.0
We can remove this at the moment.

2023-03-22 18:47 UTC, tylerfanelli commented on src/error.rs
> +/// The ra
Should this be:

`/// The raw firmware error.`?

2023-03-22 18:47 UTC, tylerfanelli commented on src/firmware/host/mod.rs
> +    os::fd::{AsRawFd, RawFd},
`clippy` tells me `std::os::fd` is a private module, and `std::os::fd::AsRawFd` does not exist.

This is news to me. Docs say they are only available on unix and WASI platforms. Since we're running on Linux, this shouldn't be a problem.

Maybe just something wrong with `cargo clippy`?

2023-03-22 18:47 UTC, tylerfanelli commented on src/error.rs
> +    RMPInitRequired = 0x0020, // 0x0020
`cargo clippy` tells me that custom discriminant values are not allowed in enums with tuple or struct variants. Thus, we need to find another way to set the error value for these two enums, `RbModeExited` and `RMPInitRequired`.

2023-03-22 18:47 UTC, tylerfanelli commented on src/tests/api.rs
> +// SPDX-License-Identifier: Apache-2.0
This entire directory should be in `tests/`, not `src/tests`.

2023-03-22 19:01 UTC, larrydewey commented on src/certs/builtin/milan/mod.rs
> +const ARK: &[u8] = include_bytes!("ark.pem");
See above

2023-03-22 19:05 UTC, larrydewey commented on src/firmware/host/mod.rs
> +    os::fd::{AsRawFd, RawFd},
I am not seeing these errors?

```bash
snp git:(ioctls) ✗ cargo clippy -- -D clippy::all
    Checking snp v0.1.0 (/home/larry/git/larrydewey/snp)
    Finished dev [unoptimized + debuginfo] target(s) in 0.69s
```

2023-03-22 19:06 UTC, larrydewey commented on src/error.rs
> +    RMPInitRequired = 0x0020, // 0x0020
I am not seeing this error, either?

2023-04-05 16:48 UTC, tylerfanelli commented on src/firmware/host/types.rs
> +    pub fn update_certs_only(certificates: Vec<CertTableEntry>) -> Self {
```suggestion
    pub fn new_certs_only(certificates: Vec<CertTableEntry>) -> Self {
```

Do you prefer this naming?

2023-04-05 16:49 UTC, tylerfanelli commented on src/firmware/host/types.rs
> +    pub fn update_config_only(config: SnpConfig) -> Self {
```suggestion
    pub fn new_config_only(config: SnpConfig) -> Self {
```

2023-04-05 16:58 UTC, tylerfanelli commented on src/firmware/linux/host/types.rs
> +    /// Creates a new isntance of a TcbVersion
```suggestion
    /// Creates a new instance of a TcbVersion
```

2023-04-05 16:59 UTC, tylerfanelli commented on src/firmware/linux/host/types.rs
> +    /// Indicates that the CHIP_ID field in the attestationr eport will always
```suggestion
    /// Indicates that the CHIP_ID field in the attestation report will always
```

2023-04-05 17:02 UTC, tylerfanelli approved these changes

2023-04-05 17:02 UTC, merged